env:
  - YII_ENV=test
language: php
php:
  - '7.1'
services:
  - mysql
test:
  adapter: mysql2
  database: tickit_user_test
  username: travis
  encoding: utf8
before_install:
  - mysql -e 'CREATE DATABASE tickit_user_test;'
install:
  - composer install
  - php yii migrate
script: vendor/bin/codecept run